import json

notebook_path = "/home/raphael/develop/mlops/sdg_hub/examples/knowledge_tuning/enhanced_summary_knowledge_tuning/document_pre_processing.ipynb"

with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

nb['cells'][2]['source'] = [
    "# Step 2: Install Required Dependencies\n",
    "# Install packages needed for document processing and text chunking\n",
    "\n",
    "#%pip install docling markdown-it-py\n",
    "#%pip install --upgrade transformers\n",
    "%pip install litellm python-dotenv"
]

new_cell_source = [
    "# Step 3 & 4: Load Documents, Chunk, and Generate Dynamic ICL\n",
    "import os\n",
    "import glob\n",
    "import json\n",
    "from typing import List\n",
    "import datasets\n",
    "from litellm import completion\n",
    "from markdown_it import MarkdownIt\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "# Load environment variables\n",
    "load_dotenv()\n",
    "\n",
    "# Multilingual configuration\n",
    "sdg_lang = os.getenv(\"SDG_LANG\", \"Portuguese (Brazil)\")\n",
    "sdg_lang_code = os.getenv(\"SDG_LANG_CODE\", \"pt-br\")\n",
    "\n",
    "# Model configuration for ICL generation (Translator Model or VLLM fallback)\n",
    "model_name = os.getenv(\"TRANSLATOR_MODEL\", os.getenv(\"VLLM_MODEL\", \"hosted_vllm/openai/RedHatAI/gpt-oss-20b\"))\n",
    "api_base = os.getenv(\"TRANSLATOR_API_BASE\", os.getenv(\"VLLM_API_BASE\"))\n",
    "api_key = os.getenv(\"TRANSLATOR_API_KEY\", os.getenv(\"VLLM_API_KEY\", \"EMPTY\"))\n",
    "\n",
    "def chunk_markdown(text: str, max_tokens: int = 200, overlap: int = 50) -> List[str]:\n",
    "    \"\"\"Splits Markdown text into chunks at block-level elements.\"\"\"\n",
    "    md = MarkdownIt()\n",
    "    tokens = md.parse(text)\n",
    "    blocks = []\n",
    "    buf = []\n",
    "    for tok in tokens:\n",
    "        if tok.block and tok.type.endswith(\"_open\"):\n",
    "            buf = []\n",
    "        elif tok.block and tok.type.endswith(\"_close\"):\n",
    "            if buf:\n",
    "                blocks.append(\"\\n\".join(buf).strip())\n",
    "                buf = []\n",
    "        elif tok.content:\n",
    "            buf.append(tok.content)\n",
    "    if buf:\n",
    "        blocks.append(\"\\n\".join(buf).strip())\n",
    "\n",
    "    chunks = []\n",
    "    current_words = []\n",
    "    for block in blocks:\n",
    "        words = block.split()\n",
    "        for w in words:\n",
    "            current_words.append(w)\n",
    "            if len(current_words) >= max_tokens:\n",
    "                chunks.append(\" \".join(current_words))\n",
    "                current_words = current_words[-overlap:] if overlap > 0 else []\n",
    "    if current_words:\n",
    "        chunks.append(\" \".join(current_words))\n",
    "    return chunks\n",
    "\n",
    "all_records = []\n",
    "md_files = glob.glob(f\"{data_dir}/*.md\")\n",
    "print(f\"Found {len(md_files)} processed markdown files in {data_dir}.\")\n",
    "\n",
    "for file_path in md_files:\n",
    "    print(f\"\\nProcessing file: {file_path}\")\n",
    "    with open(file_path, \"r\", encoding=\"utf-8\") as f:\n",
    "        text = f.read()\n",
    "        \n",
    "    chunks = chunk_markdown(text, max_tokens=5000, overlap=1000)\n",
    "    if not chunks:\n",
    "        continue\n",
    "        \n",
    "    # Get a sample paragraph (long enough to make sense) for the LLM to generate the ICL questions.\n",
    "    sample_text = next((chunk for chunk in chunks if len(chunk) > 100), chunks[0])\n",
    "    \n",
    "    prompt = f\"\"\"\n",
    "Você é um especialista em treinamento de LLMs. Analise o seguinte documento e crie exatamente 3 perguntas \n",
    "valiosas e desafiadoras que possam ser feitas com base neste texto.\n",
    "O idioma das perguntas e resumo deve ser estritamente: {sdg_lang} ({sdg_lang_code}).\n",
    "Responda APENAS com um objeto JSON válido contendo as seguintes chaves:\n",
    "\"document_outline\", \"icl_query_1\", \"icl_query_2\", \"icl_query_3\", \"domain\"\n",
    "\n",
    "Texto do Documento:\n",
    "{sample_text[:2000]}\n",
    "\n",
    "Formato JSON esperado:\n",
    "{{\n",
    "  \"document_outline\": \"Resumo de 1 frase descrevendo o escopo deste documento.\",\n",
    "  \"icl_query_1\": \"Sua pergunta numero 1?\",\n",
    "  \"icl_query_2\": \"Sua pergunta numero 2?\",\n",
    "  \"icl_query_3\": \"Sua pergunta numero 3?\",\n",
    "  \"domain\": \"Domínio do texto (ex: Finanças, Leis, TI, etc)\"\n",
    "}}\n",
    "\"\"\"\n",
    "    print(f\"  -> Generating dynamic ICL using model: {model_name}...\")\n",
    "    try:\n",
    "        response = completion(\n",
    "            model=model_name,\n",
    "            messages=[{\"role\": \"user\", \"content\": prompt}],\n",
    "            api_base=api_base,\n",
    "            api_key=api_key,\n",
    "            temperature=0.3,\n",
    "            response_format={\"type\": \"json_object\"}\n",
    "        )\n",
    "        \n",
    "        llm_output = response.choices[0].message.content\n",
    "        generated_data = json.loads(llm_output)\n",
    "        \n",
    "        icl = {\n",
    "            \"document_outline\": generated_data.get(\"document_outline\", \"Resumo do Documento\"),\n",
    "            \"icl_document\": sample_text,\n",
    "            \"icl_query_1\": generated_data.get(\"icl_query_1\", \"Pergunta 1?\"),\n",
    "            \"icl_query_2\": generated_data.get(\"icl_query_2\", \"Pergunta 2?\"),\n",
    "            \"icl_query_3\": generated_data.get(\"icl_query_3\", \"Pergunta 3?\"),\n",
    "            \"domain\": generated_data.get(\"domain\", \"Geral\")\n",
    "        }\n",
    "        print(\"  -> ICL Generated successfully!\")\n",
    "        \n",
    "    except Exception as e:\n",
    "        print(f\"  -> Error generating ICL, using fallback template. Error: {e}\")\n",
    "        icl = {\n",
    "            \"document_outline\": \"Resumo do Documento (Fallback)\",\n",
    "            \"icl_document\": sample_text,\n",
    "            \"icl_query_1\": \"Qual é o tema principal deste texto?\",\n",
    "            \"icl_query_2\": \"Quais são as principais regras ou pontos abordados?\",\n",
    "            \"icl_query_3\": \"Para quem este documento é destinado?\",\n",
    "            \"domain\": \"Geral\"\n",
    "        }\n",
    "        \n",
    "    # Append all chunks for this file using the generated file-specific ICL\n",
    "    for chunk in chunks:\n",
    "        record = {\"document\": chunk}\n",
    "        record.update(icl)\n",
    "        all_records.append(record)\n",
    "\n",
    "# Create single unified HF Dataset\n",
    "seed_data = datasets.Dataset.from_list(all_records)\n",
    "\n",
    "# Save to final output file\n",
    "seed_data.to_json(\"seed_data.jsonl\", orient=\"records\", lines=True)\n",
    "print(f\"\\nSuccessfully compiled {len(seed_data)} total chunks into seed_data.jsonl!\")\n"
]

nb['cells'][3]['source'] = new_cell_source
del nb['cells'][4]

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
    f.write('\n')
