import json
import os

notebook_path = "/home/raphael/develop/mlops/sdg_hub/examples/knowledge_tuning/enhanced_summary_knowledge_tuning/knowledge_generation.ipynb"

with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# The new function code for cell index 3
new_cell_3_source = [
    "def create_seed_data_from_document_pre_processing(seed_data_path=None):\n",
    "    \"\"\"\n",
    "    Load the seed data from the document pre-processing step.\n",
    "    \n",
    "    Args:\n",
    "        seed_data_path (str, optional): Path to the seed data file. If None, reads from env.\n",
    "        \n",
    "    Returns:\n",
    "        datasets.Dataset: The processed corpus ready for generation.\n",
    "    \"\"\"\n",
    "    # Use environment variables as defaults if not provided\n",
    "    if seed_data_path is None:\n",
    "        seed_data_path = os.getenv(\"SEED_DATA_PATH\", \"seed_data.jsonl\")\n",
    "        \n",
    "    print(f\"Loading seed data from document pre-processing: {seed_data_path}...\")\n",
    "    \n",
    "    if not os.path.exists(seed_data_path):\n",
    "        raise FileNotFoundError(\n",
    "            f\"Seed data file '{seed_data_path}' not found. \"\n",
    "            \"Please run the 'document_pre_processing.ipynb' notebook first to generate \"\n",
    "            \"the seed data from your local documents.\"\n",
    "        )\n",
    "        \n",
    "    try:\n",
    "        # Load the seed data generated by the pre-processing notebook\n",
    "        document_corpus = load_dataset(\"json\", data_files={\"train\": seed_data_path}, split=\"train\")\n",
    "        print(f\"Loaded {len(document_corpus)} document chunks ready for SDG generation.\")\n",
    "        return document_corpus\n",
    "    except Exception as e:\n",
    "        print(f\"Error loading {seed_data_path}: {e}\")\n",
    "        raise\n"
]

# The new usage code for cell index 4
new_cell_4_source = [
    "# Load seed data generated by the previous notebook\n",
    "seed_data_path = os.getenv(\"SEED_DATA_PATH\", \"seed_data.jsonl\")\n",
    "\n",
    "document_corpus = create_seed_data_from_document_pre_processing(\n",
    "    seed_data_path=seed_data_path\n",
    ")\n",
    "\n",
    "# Subsample the seed data. Useful for debugging.\n",
    "subsample = int(os.getenv(\"SEED_DATA_SUBSAMPLE\", \"0\"))\n",
    "if subsample > 0 and subsample < len(document_corpus):\n",
    "    print(f\"Subsampling: using only {subsample} chunks for generation.\")\n",
    "    document_corpus = document_corpus.select(range(subsample))\n",
    "\n",
    "document_corpus = document_corpus.to_pandas()\n"
]

nb['cells'][3]['source'] = new_cell_3_source
nb['cells'][4]['source'] = new_cell_4_source

# Iterate over all other cells and replace 'quality_corpus' with 'document_corpus'
for cell in nb['cells']:
    if 'source' in cell:
        # source is a list of strings
        updated_source = []
        for line in cell['source']:
            # Replace occurrences
            line = line.replace('quality_corpus', 'document_corpus')
            updated_source.append(line)
        cell['source'] = updated_source

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
    f.write('\\n')

print("Update completed successfully.")
